spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    代码生成通过读取driverClassName来判断数据库类型
    driverClassName: com.mysql.cj.jdbc.Driver
#    driverClassName: oracle.jdbc.driver.OracleDriver
    druid:
      first:  #数据源1
        url: jdbc:mysql://localhost:3306/platform-plus?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
#        url: jdbc:oracle:thin:@localhost:1521:platform
#        username: platform
#        password: 123456
      second:  #数据源2
        url: jdbc:mysql://localhost:3306/platform-plus?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
#        url: jdbc:oracle:thin:@localhost:1521:platform
#        username: platform
#        password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: 123456
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
