spring:
  datasource:
    url: jdbc:mysql://devdb.meilyhome.com:3305/tongyi-cms?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: sendmiss
  mail:
    host: smtp.qq.com
    protocol: smtp
    port: 465
    username: 147657060@qq.com
    password: hlxamiafvwotcahf
