spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://devdb.meilyhome.com:3305/platform-plus?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sendmiss
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: ExpendHikariCP
      max-lifetime: 28700000 #1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

platform:
  file:
    path: file:D:/usr/local/nginx/html/upload/