spring:
  datasource:
    url: jdbc:mysql://devdb.meilyhome.com:3305/platform-plus?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: sendmiss
  mail:
    host: smtp.qq.com
    protocol: smtp
    port: 465
    username: 147657060@qq.com
    password: hlxamiafvwotcahf
platform:
  file:
    path: file:D:/usr/local/nginx/html/upload/