spring:
  cache:
    type: none # none| redis |mongdb? |ehcache?
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:    # 密码（默认为空）
    timeout: 100ms  # 连接超时时长（毫秒）
    expire-time: 180000ms # redis过期时间是30分钟30*60
    jedis:
      pool:
        max-active: 10000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接
  data:
    mongodb:
      repositories:
        enabled: false
    redis:
      repositories:
        enabled: false
logging:
  level:
    com: info
