spring:
  datasource:
    url: jdbc:mysql://devdb.tdocker.top:3305/db?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abcdefg
  mail:
    host: smtp.qq.com
    protocol: smtp
    port: 465
    username: 147657060@qq.com
    password: abcdefg
tongyi:
  file:
    path: file:D:/usr/local/nginx/html/upload/