spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://devdb.tdocker.top:3305/db?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: abcdefg
    hikari:
      minimum-idle: 10
      maximum-pool-size: 25
      auto-commit: true
      idle-timeout: 30000
      pool-name: ExpendHikariCP
      max-lifetime: 28700000 #1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1