DROP TABLE IF EXISTS `WX_ARTICLE`;
CREATE TABLE `WX_ARTICLE`  (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TYPE` TINYINT(1) NULL DEFAULT 1 COMMENT '文章类型[1:普通文章,5:帮助中心]',
  `TITLE` VARCHAR(1024) CHARACTER SET UTF8 NOT NULL COMMENT '标题',
  `SUMMARY` VARCHAR(1024) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '文章摘要',
  `TAGS` VARCHAR(255) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '文章标签',
  `CONTENT` LONGTEXT CHARACTER SET UTF8 NULL COMMENT '内容',
  `CATEGORY` VARCHAR(25) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '分类',
  `SUB_CATEGORY` VARCHAR(25) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '二级目录',
  `CREATE_TIME` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  `UPDATE_TIME` DATETIME(0) NULL DEFAULT NULL COMMENT '修改时间',
  `OPEN_COUNT` INT(11) NULL DEFAULT 0 COMMENT '点击次数',
  `START_TIME` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '生效时间',
  `END_TIME` DATETIME(0) NULL DEFAULT NULL COMMENT '失效时间',
  `TARGET_LINK` VARCHAR(255) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '指向外链',
  `IMAGE` VARCHAR(255) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '文章首图',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_TITLE`(`TITLE`) USING BTREE COMMENT '标题不得重复'
) ENGINE = INNODB AUTO_INCREMENT = 337 CHARACTER SET = UTF8 COMMENT = 'CMS文章中心' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- TABLE STRUCTURE FOR WX_ACCOUNT
-- ----------------------------
DROP TABLE IF EXISTS `WX_ACCOUNT`;
CREATE TABLE `WX_ACCOUNT`  (
  `APPID` CHAR(20) CHARACTER SET UTF8 NOT NULL COMMENT 'APPID',
  `NAME` VARCHAR(50) CHARACTER SET UTF8 NOT NULL COMMENT '公众号名称',
  `TYPE` TINYINT(1) UNSIGNED NULL DEFAULT 1 COMMENT '账号类型',
  `VERIFIED` TINYINT(1) UNSIGNED NULL DEFAULT 1 COMMENT '认证状态',
  `SECRET` CHAR(32) CHARACTER SET UTF8 NOT NULL COMMENT 'APPSECRET',
  `TOKEN` VARCHAR(32) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT 'TOKEN',
  `AES_KEY` VARCHAR(43) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT 'AESKEY',
  PRIMARY KEY (`APPID`) USING BTREE
) ENGINE = INNODB CHARACTER SET = UTF8 COMMENT = '公众号账号' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- TABLE STRUCTURE FOR WX_MSG
-- ----------------------------
DROP TABLE IF EXISTS `WX_MSG`;
CREATE TABLE `WX_MSG`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `APPID` CHAR(20) CHARACTER SET UTF8 NOT NULL COMMENT 'APPID',
  `OPENID` VARCHAR(32) CHARACTER SET UTF8 NOT NULL COMMENT '微信用户ID',
  `IN_OUT` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT '消息方向',
  `MSG_TYPE` CHAR(25) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '消息类型',
  `DETAIL` VARCHAR(255) NULL COMMENT '消息详情',
  `CREATE_TIME` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0) COMMENT '创建时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_APPID`(`APPID`) USING BTREE COMMENT 'APPID'
) ENGINE = INNODB AUTO_INCREMENT = 9 CHARACTER SET = UTF8MB4 COMMENT = '微信消息' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- TABLE STRUCTURE FOR WX_MSG_REPLY_RULE
-- ----------------------------
DROP TABLE IF EXISTS `MSG_REPLY_RULE`;
DROP TABLE IF EXISTS `WX_MSG_REPLY_RULE`;
CREATE TABLE `WX_MSG_REPLY_RULE`  (
  `RULE_ID` INT(11) NOT NULL AUTO_INCREMENT,
  `APPID` CHAR(20) CHARACTER SET UTF8 NULL DEFAULT '' COMMENT 'APPID',
  `RULE_NAME` VARCHAR(20) CHARACTER SET UTF8 NOT NULL COMMENT '规则名称',
  `MATCH_VALUE` VARCHAR(200) CHARACTER SET UTF8 NOT NULL COMMENT '匹配的关键词、事件等',
  `EXACT_MATCH` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否精确匹配',
  `REPLY_TYPE` VARCHAR(20) CHARACTER SET UTF8 NOT NULL DEFAULT '1' COMMENT '回复消息类型',
  `REPLY_CONTENT` VARCHAR(1024) CHARACTER SET UTF8 NOT NULL COMMENT '回复消息内容',
  `STATUS` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '规则是否有效',
  `DESC` VARCHAR(255) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '备注说明',
  `EFFECT_TIME_START` TIME(0) NULL DEFAULT '00:00:00' COMMENT '生效起始时间',
  `EFFECT_TIME_END` TIME(0) NULL DEFAULT '23:59:59' COMMENT '生效结束时间',
  `PRIORITY` INT(3) UNSIGNED NULL DEFAULT 0 COMMENT '规则优先级',
  `UPDATE_TIME` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`RULE_ID`) USING BTREE,
  INDEX `IDX_APPID`(`APPID`) USING BTREE COMMENT 'APPID'
) ENGINE = INNODB AUTO_INCREMENT = 36 CHARACTER SET = UTF8 COMMENT = '自动回复规则' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- RECORDS OF WX_MSG_REPLY_RULE
-- ----------------------------
INSERT INTO `WX_MSG_REPLY_RULE` VALUES (1, '', '关注公众号', 'SUBSCRIBE', 0, 'TEXT', '你好，欢迎关注！\N<A HREF=\"HTTPS://GITHUB.COM/NIEFY\">点击链接查看我的主页</A>', 1, '关注回复', '00:00:00', '23:59:59', 0, '2020-05-20 15:15:00');

-- ----------------------------
-- TABLE STRUCTURE FOR WX_MSG_TEMPLATE
-- ----------------------------
DROP TABLE IF EXISTS `MSG_TEMPLATE`;
DROP TABLE IF EXISTS `WX_MSG_TEMPLATE`;
CREATE TABLE `WX_MSG_TEMPLATE`  (
  `ID` BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `APPID` CHAR(20) CHARACTER SET UTF8 NOT NULL COMMENT 'APPID',
  `TEMPLATE_ID` VARCHAR(100) CHARACTER SET UTF8 NOT NULL COMMENT '公众号模板ID',
  `NAME` VARCHAR(50) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '模版名称',
  `TITLE` VARCHAR(20) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '标题',
  `CONTENT` TEXT CHARACTER SET UTF8 NULL COMMENT '模板内容',
  `DATA` VARCHAR(255) NULL COMMENT '消息内容',
  `URL` VARCHAR(255) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '链接',
  `MINIPROGRAM` VARCHAR(255) NULL COMMENT '小程序信息',
  `STATUS` TINYINT(1) UNSIGNED NOT NULL COMMENT '是否有效',
  `UPDATE_TIME` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '修改时间',
  PRIMARY KEY (`ID`) USING BTREE,
  UNIQUE INDEX `IDX_NAME`(`NAME`) USING BTREE COMMENT '模板名称',
  INDEX `IDX_STATUS`(`STATUS`) USING BTREE COMMENT '模板状态',
  INDEX `IDX_APPID`(`APPID`) USING BTREE COMMENT 'APPID'
) ENGINE = INNODB AUTO_INCREMENT = 62 CHARACTER SET = UTF8 COMMENT = '消息模板' ROW_FORMAT = DYNAMIC;


-- ----------------------------
-- TABLE STRUCTURE FOR WX_QR_CODE
-- ----------------------------
DROP TABLE IF EXISTS `WX_QR_CODE`;
CREATE TABLE `WX_QR_CODE`  (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `APPID` CHAR(20) CHARACTER SET UTF8 NOT NULL COMMENT 'APPID',
  `IS_TEMP` TINYINT(1) NULL DEFAULT NULL COMMENT '是否为临时二维码',
  `SCENE_STR` VARCHAR(64) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '场景值ID',
  `TICKET` VARCHAR(255) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '二维码TICKET',
  `URL` VARCHAR(255) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '二维码图片解析后的地址',
  `EXPIRE_TIME` DATETIME(0) NULL DEFAULT NULL COMMENT '该二维码失效时间',
  `CREATE_TIME` DATETIME(0) NULL DEFAULT NULL COMMENT '该二维码创建时间',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_APPID`(`APPID`) USING BTREE COMMENT 'APPID'
) ENGINE = INNODB AUTO_INCREMENT = 4 CHARACTER SET = UTF8MB4 COMMENT = '公众号带参二维码' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- TABLE STRUCTURE FOR WX_TEMPLATE_MSG_LOG
-- ----------------------------
DROP TABLE IF EXISTS `WX_TEMPLATE_MSG_LOG`;
CREATE TABLE `WX_TEMPLATE_MSG_LOG`  (
  `LOG_ID` BIGINT(11) NOT NULL AUTO_INCREMENT COMMENT 'ID',
  `APPID` CHAR(20) CHARACTER SET UTF8 NOT NULL COMMENT 'APPID',
  `TOUSER` VARCHAR(50) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '用户OPENID',
  `TEMPLATE_ID` VARCHAR(50) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT 'TEMPLATEID',
  `DATA` VARCHAR(255) NULL COMMENT '消息数据',
  `URL` VARCHAR(255) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '消息链接',
  `MINIPROGRAM` VARCHAR(255) NULL COMMENT '小程序信息',
  `SEND_TIME` DATETIME(0) NULL DEFAULT NULL COMMENT '发送时间',
  `SEND_RESULT` VARCHAR(255) CHARACTER SET UTF8 NULL DEFAULT NULL COMMENT '发送结果',
  PRIMARY KEY (`LOG_ID`) USING BTREE,
  INDEX `IDX_APPID`(`APPID`) USING BTREE COMMENT 'APPID'
) ENGINE = INNODB AUTO_INCREMENT = 116250 CHARACTER SET = UTF8 COMMENT = '微信模版消息发送记录' ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- TABLE STRUCTURE FOR WX_USER
-- ----------------------------
DROP TABLE IF EXISTS `WX_USER`;
CREATE TABLE `WX_USER`  (
  `OPENID` VARCHAR(50) CHARACTER SET UTF8MB4 NOT NULL COMMENT '微信OPENID',
  `APPID` CHAR(20) CHARACTER SET UTF8 NOT NULL COMMENT 'APPID',
  `PHONE` CHAR(11) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '手机号',
  `NICKNAME` VARCHAR(50) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '昵称',
  `SEX` TINYINT(4) NULL DEFAULT NULL COMMENT '性别(0-未知、1-男、2-女)',
  `CITY` VARCHAR(20) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '城市',
  `PROVINCE` VARCHAR(255) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '省份',
  `HEADIMGURL` VARCHAR(1000) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '头像',
  `SUBSCRIBE_TIME` DATETIME(0) NULL DEFAULT NULL COMMENT '订阅时间',
  `SUBSCRIBE` TINYINT(3) UNSIGNED NULL DEFAULT 1 COMMENT '是否关注',
  `UNIONID` VARCHAR(50) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT 'UNIONID',
  `REMARK` VARCHAR(255) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '备注',
  `TAGID_LIST` VARCHAR(1000) NULL COMMENT '标签ID列表',
  `SUBSCRIBE_SCENE` VARCHAR(50) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '关注场景',
  `QR_SCENE_STR` VARCHAR(64) CHARACTER SET UTF8MB4 NULL DEFAULT NULL COMMENT '扫码场景值',
  PRIMARY KEY (`OPENID`) USING BTREE,
  INDEX `IDX_UNIONID`(`UNIONID`) USING BTREE COMMENT 'UNIONID',
  INDEX `IDX_APPID`(`APPID`) USING BTREE COMMENT 'APPID'
) ENGINE = INNODB CHARACTER SET = UTF8MB4 COMMENT = '用户表' ROW_FORMAT = DYNAMIC;


INSERT INTO `SYS_MENU` VALUES ('16', '0', '微信管理', NULL, NULL, 0, 'admin', 1,1);
INSERT INTO `SYS_MENU` VALUES ('1601', '16', '公众号菜单', 'wx/wx-menu', '', 1, 'log', 0,1);
INSERT INTO `SYS_MENU` VALUES ('160101', '1601', '更新公众号菜单', '', 'wx:menu:save', 2, '', 0,1);

INSERT INTO `SYS_MENU` VALUES ('1602', '16', '素材管理', 'wx/wx-assets', '', 1, '', 0,1);
INSERT INTO `SYS_MENU` VALUES ('160201', '1602', '查看', '', 'wx:wxassets:list', 2, '', 0,1);
INSERT INTO `SYS_MENU` VALUES ('160202', '1602', '新增修改', '', 'wx:wxassets:save', 2, '', 0,1);
INSERT INTO `SYS_MENU` VALUES ('160203', '1602', '删除', '', 'wx:wxassets:delete', 2, '', 0,1);

INSERT INTO `SYS_MENU` VALUES ('1603', '16', '自动回复规则', 'wx/msg-reply-rule', NULL, 1, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160301', '1603', '查看', NULL, 'wx:msgreplyrule:list,wx:msgreplyrule:info', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160302', '1603', '新增', NULL, 'wx:msgreplyrule:save', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160303', '1603', '修改', NULL, 'wx:msgreplyrule:update', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160304', '1603', '删除', NULL, 'wx:msgreplyrule:delete', 2, 'admin', 6,1);

INSERT INTO `SYS_MENU` VALUES ('1604', '16', '模板消息', 'wx/msg-template', NULL, 1, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160401', '1604', '查看', NULL, 'wx:msgtemplate:list,wx:msgtemplate:info', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160402', '1604', '新增', NULL, 'wx:msgtemplate:save', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160403', '1604', '修改', NULL, 'wx:msgtemplate:update', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160404', '1604', '删除', NULL, 'wx:msgtemplate:delete', 2, 'admin', 6,1);

INSERT INTO `SYS_MENU` VALUES ('1605', '16', '带参二维码', 'wx/wx-qrcode', NULL, 1, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160501', '1605', '查看', NULL, 'wx:wxqrcode:list,wx:wxqrcode:info', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160502', '1605', '新增', NULL, 'wx:wxqrcode:save', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160503', '1605', '删除', NULL, 'wx:wxqrcode:delete', 2, 'admin', 6,1);

INSERT INTO `SYS_MENU` VALUES ('1606', '16', '粉丝管理', 'wx/wx-user', NULL, 1, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160601', '1606', '查看', NULL, 'wx:wxuser:list,wx:wxuser:info', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160602', '1606', '删除', NULL, 'wx:wxuser:delete', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160603', '1606', '同步', '', 'wx:wxuser:save', 2, 'admin', 6,1);

INSERT INTO `SYS_MENU` VALUES ('1607', '16', '公众号消息', 'wx/wx-msg', NULL, 1, '', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160701', '1607', '查看', NULL, 'wx:wxmsg:list,wx:wxmsg:info', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160702', '1607', '新增', NULL, 'wx:wxmsg:save', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160703', '1607', '删除', NULL, 'wx:wxmsg:delete', 2, 'admin', 6,1);

INSERT INTO `SYS_MENU` VALUES ('1608', '16', '公众号账号', 'wx/wx-account', NULL, 1, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160801', '1608', '查看', NULL, 'wx:wxaccount:list,wx:wxaccount:info', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160802', '1608', '新增', NULL, 'wx:wxaccount:save', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160803', '1608', '修改', NULL, 'wx:wxaccount:update', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('160804', '1608', '删除', NULL, 'wx:wxaccount:delete', 2, 'admin', 6,1);

INSERT INTO `SYS_MENU` VALUES ('1609', '16', '内容管理', '', '', 0, 'admin', 2,1);
INSERT INTO `SYS_MENU` VALUES ('160901', '1609', '文章管理', 'wx/article', NULL, 1, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('16090101', '160901', '查看', NULL, 'wx:article:list,wx:article:info', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('16090102', '160901', '新增', NULL, 'wx:article:save', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('16090103', '160901', '修改', NULL, 'wx:article:update', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('16090104', '160901', '删除', NULL, 'wx:article:delete', 2, 'admin', 6,1);

INSERT INTO `SYS_MENU` VALUES ('1610', '16', '日志报表', '', '', 0, 'admin', 4,1);
INSERT INTO `SYS_MENU` VALUES ('161001', '1610', '模版消息发送记录', 'wx/template-msg-log', NULL, 1, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('16100101', '161001', '列表', NULL, 'wx:templatemsglog:list', 2, 'admin', 6,1);
INSERT INTO `SYS_MENU` VALUES ('16100102', '161001', '删除', NULL, 'wx:templatemsglog:delete', 2, 'admin', 6,1);